# File: serverless.yml
# Type: Server Configuration
# Configures Serverless on AWS.

service: slide-auth-server

provider:
  name: aws
  runtime: nodejs6.10
  profile: slide
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:*:*:table/streamers"

functions:
  anonymous:
    handler: handlers/users.anonymous
    events:
      - http:
          path: users/anonymous
          method: POST
          cors: true
  register:
    handler: handlers/users.register
    events:
      - http:
          path: users/register
          method: POST
          cors: true
  update:
    handler: handlers/users.update
    events:
      - http:
          path: users/update
          method: POST
          cors: true
  batch:
    handler: handlers/users.batch
    events:
      - http:
          path: users/batch
          method: POST
          cors: true
  login:
    handler: handlers/auth.login
    events:
      - http:
          path: auth/login
          method: POST
          cors: true

resources:
  Resources:
    AuthTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: username
            AttributeType: S
        KeySchema:
          -
            AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10
        TableName: streamers
